/** IPC channel 名称常量，Main 与 Preload 必须一致 */

export const IPC = {
  TASKS_LIST: 'tasks:list',
  TASKS_GET: 'tasks:get',
  TASKS_GET_IN_TRASH: 'tasks:getInTrash',
  TASKS_CREATE: 'tasks:create',
  TASKS_UPDATE: 'tasks:update',
  TASKS_DELETE: 'tasks:delete',
  TASKS_RESTORE: 'tasks:restore',
  TASKS_PERMANENT_DELETE: 'tasks:permanentDelete',
  TASKS_EMPTY_TRASH: 'tasks:emptyTrash',
  TASKS_COUNT_TRASH: 'tasks:countTrash',
  TASKS_COUNT_DONE: 'tasks:countDone',
  TASKS_REORDER: 'tasks:reorder',
  KANBAN_GROUPS_LIST: 'kanbanGroups:list',
  KANBAN_GROUPS_CREATE: 'kanbanGroups:create',
  KANBAN_GROUPS_UPDATE: 'kanbanGroups:update',
  KANBAN_GROUPS_DELETE: 'kanbanGroups:delete',
  CATEGORIES_LIST: 'categories:list',
  CATEGORIES_CREATE: 'categories:create',
  CATEGORIES_UPDATE: 'categories:update',
  CATEGORIES_DELETE: 'categories:delete',
  CATEGORIES_REORDER: 'categories:reorder',
  TAGS_LIST: 'tags:list',
  APP_GET_DATA_PATH: 'app:getDataPath',
  APP_SET_DATA_PATH: 'app:setDataPath',
  /** 系统文件夹选择器，用于设置数据目录 */
  APP_PICK_DATA_DIR: 'app:pickDataDir',
  APP_EXPORT_USER_CONFIG: 'app:exportUserConfig',
  APP_IMPORT_USER_CONFIG: 'app:importUserConfig',
  APP_GET_VERSION: 'app:getVersion',
  APP_GET_INFO: 'app:getInfo',
  /** Main → Renderer：托盘/菜单触发新建任务（兼容旧版） */
  APP_NEW_TASK: 'app:new-task',
  /** Main → Renderer：快捷键/托盘触发的统一动作 */
  APP_ACTION: 'app:action',
  APP_GET_SHORTCUTS: 'app:getShortcuts',
  APP_SET_SHORTCUTS: 'app:setShortcuts',
  APP_GET_LLM_CONFIG: 'app:getLlmConfig',
  APP_SET_LLM_CONFIG: 'app:setLlmConfig',
  APP_GET_AI_PROMPT: 'app:getAiPrompt',
  APP_SET_AI_PROMPT: 'app:setAiPrompt',
  /** 按设置解析任务文本（本地 / LLM，失败回落） */
  APP_PARSE_TASK_INPUT: 'app:parseTaskInput',
  APP_GET_CLOSE_BEHAVIOR: 'app:getCloseBehavior',
  APP_SET_CLOSE_BEHAVIOR: 'app:setCloseBehavior',
  APP_CLOSE_REQUEST: 'app:closeRequest',
  APP_CONFIRM_CLOSE: 'app:confirmClose',
  APP_SHOW_WINDOW: 'app:showWindow',
  /** 系统文件选择器 → 复制到 data/attachments */
  APP_PICK_ATTACHMENT: 'app:pickAttachment',
  /** 将 base64 缓冲区写入 attachments（粘贴图片等） */
  APP_SAVE_ATTACHMENT: 'app:saveAttachment',
  /** 附件 URI → file:// 供预览渲染 */
  APP_RESOLVE_ATTACHMENT_URL: 'app:resolveAttachmentUrl',
  /** 用系统默认程序打开附件 */
  APP_OPEN_ATTACHMENT: 'app:openAttachment',
  /** 附件另存为到用户指定路径 */
  APP_DOWNLOAD_ATTACHMENT: 'app:downloadAttachment',
  /** Main → Renderer：新应用内消息 */
  APP_MESSAGE_PUSH: 'app:message-push',
  MESSAGES_LIST: 'messages:list',
  MESSAGES_COUNT_UNREAD: 'messages:countUnread',
  MESSAGES_MARK_READ: 'messages:markRead',
  MESSAGES_MARK_ALL_READ: 'messages:markAllRead',
  SCHEDULED_SUMMARIES_LIST: 'scheduledSummaries:list',
  SCHEDULED_SUMMARIES_CREATE: 'scheduledSummaries:create',
  SCHEDULED_SUMMARIES_UPDATE: 'scheduledSummaries:update',
  SCHEDULED_SUMMARIES_DELETE: 'scheduledSummaries:delete',
  SCHEDULED_SUMMARIES_PREVIEW: 'scheduledSummaries:preview',
  SCHEDULED_SUMMARIES_RUN_NOW: 'scheduledSummaries:runNow',
  /** 日历法定放假 / 调休上班标注（按年份批量） */
  HOLIDAYS_CALENDAR_MARKS: 'holidays:calendarMarks',
  /** 节假日缓存状态（来源 / 年份 / mtime） */
  HOLIDAYS_STATUS: 'holidays:status',
  /** 强制刷新指定年份节假日缓存 */
  HOLIDAYS_REFRESH: 'holidays:refresh',
  TASK_VIEWS_LIST: 'taskViews:list',
  TASK_VIEWS_CREATE: 'taskViews:create',
  TASK_VIEWS_UPDATE: 'taskViews:update',
  TASK_VIEWS_DELETE: 'taskViews:delete',
  TASK_VIEWS_PREVIEW_COUNT: 'taskViews:previewCount',
  TASK_VIEWS_CREATE_FROM_TEMPLATE: 'taskViews:createFromTemplate',
  TASK_ACTIVITIES_LIST_BY_TASK: 'taskActivities:listByTask',
  TASK_ACTIVITIES_COUNT: 'taskActivities:count',
  TASK_ACTIVITIES_DELETE_ALL: 'taskActivities:deleteAll',
  TASK_ACTIVITIES_PURGE: 'taskActivities:purge',
  TASK_ACTIVITIES_DELETE_TRASHED: 'taskActivities:deleteTrashed',
  TASK_ACTIVITY_RETENTION_GET: 'taskActivityRetention:get',
  TASK_ACTIVITY_RETENTION_SET: 'taskActivityRetention:set',
  WIDGET_TOGGLE: 'widget:toggle',
  WIDGET_SHOW: 'widget:show',
  WIDGET_HIDE: 'widget:hide',
  WIDGET_GET_SETTINGS: 'widget:getSettings',
  WIDGET_UPDATE_SETTINGS: 'widget:updateSettings',
  WIDGET_INSTANCES_LIST: 'widgetInstances:list',
  WIDGET_INSTANCES_GET: 'widgetInstances:get',
  WIDGET_INSTANCES_CREATE: 'widgetInstances:create',
  WIDGET_INSTANCES_UPDATE: 'widgetInstances:update',
  WIDGET_INSTANCES_DELETE: 'widgetInstances:delete',
  WIDGET_INSTANCE_SHOW: 'widgetInstance:show',
  WIDGET_INSTANCE_HIDE: 'widgetInstance:hide',
  WIDGET_INSTANCE_TOGGLE: 'widgetInstance:toggle',
  WIDGET_INSTANCE_EXPAND: 'widgetInstance:expand',
  WIDGET_INSTANCE_COLLAPSE: 'widgetInstance:collapse',
  WIDGET_INSTANCE_SET_DISPLAY_MODE: 'widgetInstance:setDisplayMode',
  /** Main → Widget：展示状态变更 */
  WIDGET_DISPLAY_MODE_CHANGED: 'widget:displayModeChanged',
  WIDGET_NOTES_LIST: 'widgetNotes:list',
  WIDGET_NOTES_CREATE: 'widgetNotes:create',
  WIDGET_NOTES_UPDATE: 'widgetNotes:update',
  WIDGET_NOTES_DELETE: 'widgetNotes:delete',
  WIDGET_NOTES_CONVERT_TO_TASK: 'widgetNotes:convertToTask',
  CAPTURE_TOGGLE: 'capture:toggle',
  CAPTURE_SHOW: 'capture:show',
  CAPTURE_HIDE: 'capture:hide',
  /** Main → Capture：聚焦输入框 */
  CAPTURE_FOCUS: 'capture:focus',
  APP_OPEN_MAIN: 'app:openMain',
  /** Main → Renderer：打开指定路由 */
  APP_NAVIGATE: 'app:navigate',
  /** 云同步：登录 / 登出 / 状态 / 触发 / 服务器地址 / 偏好 / 测连 */
  SYNC_LOGIN: 'sync:login',
  SYNC_LOGOUT: 'sync:logout',
  SYNC_GET_STATUS: 'sync:getStatus',
  SYNC_TRIGGER: 'sync:trigger',
  SYNC_SET_SERVER_URL: 'sync:setServerUrl',
  SYNC_SET_PREFERENCES: 'sync:setPreferences',
  SYNC_TEST_SERVER_URL: 'sync:testServerUrl',
  SYNC_REPORT_UI_PREFERENCES: 'sync:reportUiPreferences',
  /** Main → Renderer：远端应用了 UI 偏好 */
  SYNC_UI_PREFERENCES_APPLIED: 'sync:uiPreferencesApplied',
  /** 通知管理 */
  NOTIFY_GET_CONFIG: 'notify:getConfig',
  NOTIFY_SET_CONFIG: 'notify:setConfig',
  NOTIFY_TEST_IYUU: 'notify:testIyuu',
  NOTIFY_TEST_WEBHOOK: 'notify:testWebhook',
  NOTIFY_LIST_DELIVERIES: 'notify:listDeliveries',
  NOTIFY_LIST_PENDING: 'notify:listPending',
  /** 自动更新 */
  APP_UPDATE_GET_STATUS: 'appUpdate:getStatus',
  APP_UPDATE_CHECK: 'appUpdate:check',
  APP_UPDATE_QUIT_AND_INSTALL: 'appUpdate:quitAndInstall',
  /** Main → Renderer：更新状态推送 */
  APP_UPDATE_STATUS: 'appUpdate:status'
} as const
